
name: Build & Release

on:
  push:
    branches: [main]
    paths:
      - '**.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Cache Dependencies
        run: deno cache --unstable ghfetch.ts

      - name: Build
        run: |
          deno compile --unstable -A --lite --quiet -o ghfetch-windows-x86_64 --target x86_64-pc-windows-msvc ghfetch.ts
          deno compile --unstable -A --lite --quiet -o ghfetch-linux-gnu-x86_64 --target x86_64-unknown-linux-gnu ghfetch.ts
          deno compile --unstable -A --lite --quiet -o ghfetch-darwin-x86_64 --target x86_64-apple-darwin ghfetch.ts
          deno compile --unstable -A --lite --quiet -o ghfetch-darwin-aarch64 --target aarch64-apple-darwin ghfetch.ts
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          files: |
            LICENSE
            ghfetch-windows-x86_64.exe
            ghfetch-linux-gnu-x86_64
            ghfetch-darwin-x86_64
            ghfetch-darwin-aarch64
